repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  name: cauldron-app
  description: Cauldron Application
  homepage: https://github.com/cauldron-app/cauldron-app
  private: true
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: feature
    color: 0075ca
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: good first issue
    color: 7057ff
    description: Good for newcomers

# Branch protection rules
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: ["Lint", "Type Check", "Test", "E2E Tests"]
      enforce_admins: true
      restrictions: null
  
  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: ["Lint", "Type Check", "Test"]
      enforce_admins: false
      restrictions: null
